// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tonko_Zsanett_Proiect.Data;

#nullable disable

namespace Tonko_Zsanett_Proiect.Migrations
{
    [DbContext(typeof(Tonko_Zsanett_ProiectContext))]
    [Migration("20240107171523_Cumparat")]
    partial class Cumparat
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Tonko_Zsanett_Proiect.Models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("Tonko_Zsanett_Proiect.Models.Cumparat", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int?>("ProdusID")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ProdusID")
                        .IsUnique()
                        .HasFilter("[ProdusID] IS NOT NULL");

                    b.HasIndex("UserID");

                    b.ToTable("Cumparat");
                });

            modelBuilder.Entity("Tonko_Zsanett_Proiect.Models.Furnizor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("NumeFurnizor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Furnizor");
                });

            modelBuilder.Entity("Tonko_Zsanett_Proiect.Models.Produs", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int?>("CumparatID")
                        .HasColumnType("int");

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FurnizorID")
                        .HasColumnType("int");

                    b.Property<decimal>("Pret")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("ID");

                    b.HasIndex("FurnizorID");

                    b.ToTable("Produs");
                });

            modelBuilder.Entity("Tonko_Zsanett_Proiect.Models.ProdusCategory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<int>("ProdusID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("ProdusID");

                    b.ToTable("ProdusCategory");
                });

            modelBuilder.Entity("Tonko_Zsanett_Proiect.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Adresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Tonko_Zsanett_Proiect.Models.Cumparat", b =>
                {
                    b.HasOne("Tonko_Zsanett_Proiect.Models.Produs", "Produs")
                        .WithOne("Cumparat")
                        .HasForeignKey("Tonko_Zsanett_Proiect.Models.Cumparat", "ProdusID");

                    b.HasOne("Tonko_Zsanett_Proiect.Models.User", "User")
                        .WithMany("Cumparate")
                        .HasForeignKey("UserID");

                    b.Navigation("Produs");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tonko_Zsanett_Proiect.Models.Produs", b =>
                {
                    b.HasOne("Tonko_Zsanett_Proiect.Models.Furnizor", "Furnizor")
                        .WithMany("Produse")
                        .HasForeignKey("FurnizorID");

                    b.Navigation("Furnizor");
                });

            modelBuilder.Entity("Tonko_Zsanett_Proiect.Models.ProdusCategory", b =>
                {
                    b.HasOne("Tonko_Zsanett_Proiect.Models.Category", "Category")
                        .WithMany("ProdusCategories")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tonko_Zsanett_Proiect.Models.Produs", "Produs")
                        .WithMany("ProdusCategories")
                        .HasForeignKey("ProdusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Produs");
                });

            modelBuilder.Entity("Tonko_Zsanett_Proiect.Models.Category", b =>
                {
                    b.Navigation("ProdusCategories");
                });

            modelBuilder.Entity("Tonko_Zsanett_Proiect.Models.Furnizor", b =>
                {
                    b.Navigation("Produse");
                });

            modelBuilder.Entity("Tonko_Zsanett_Proiect.Models.Produs", b =>
                {
                    b.Navigation("Cumparat");

                    b.Navigation("ProdusCategories");
                });

            modelBuilder.Entity("Tonko_Zsanett_Proiect.Models.User", b =>
                {
                    b.Navigation("Cumparate");
                });
#pragma warning restore 612, 618
        }
    }
}
